[GENERAL]
# Taille des fragments en octets (8, 4, etc.)
CHUNK_SIZE = 8

# Liste des registres à analyser (les registres doivent être séparés par des espaces)
# Registres essentiels pour capturer les secrets
REGISTERS = REG_RIP REG_RAX REG_RSI REG_RDI

# Octets lues en mémoire
# Valeurs autorisées : 0, 8, 16 et 32 (0 = désactivé)
MEMORY = 32

ENDIANNESS = big
# Valeurs autorisées : little / big

#Commande permettant de récupérer le secret
# Extrait uniquement les secrets (3e colonne) de key.log et les concatène en hex
COMMAND = echo "e3:f3:2f:1d:bd:cd:f2:d1:fe:89:19:1a:d6:a7:6b:b3:e6:5f:62:2a:19:e2:67:87:69:1f:e1:28:f9:03:ee:39:cc:6f:13:07:88:89:fd:96:23:a3:5d:69:3f:29:a2:6a"

# Option pour activer/désactiver les logs détaillés (True ou False)
VERBOSE = False

[FILTERS]
# Mode de filtrage des bibliothèques
# Valeurs autorisées :
#   whitelist  -> instrumente SEULEMENT les libs listées dans TARGET_LIB
#   blacklist  -> instrumente tout SAUF les libs listées dans FILTER_LIB
#   none       -> aucun filtre, tout est instrumenté
MODE = blacklist

# Fonctions à ne pas tracer
FILTER_FUNCTION = printf, sprintf, puts, SSL_sendfile

# Bibliothèques système à ne pas tracer dans le mode blacklist
FILTER_LIB = ntdll.dll

# Bibliothèques à tracer dans le mode whitelist (séparées par des virgules)
TARGET_LIB = libssl-3-x64.dll, libcrypto-3-x64.dll

# Mode de filtrage
# Valeurs autorisées : min_fragments / max_fragments / max_contiguous / reg_priority / closest_address
FILTER_METHOD = partial

# Arguments
# pour reg_priority, une liste reg:score séparés par des virgules
# ici, on préfère REG_RAX (score=1) puis REG_RDI (2), et on met MEMORY32 plus bas
FILTER_OPTION = 1

[INPUT FILES]
# Chemin vers le fichier binaire à analyser
BINARY_FILE = data/log/trace.binary

# Chemin vers le fichier log de Pin (par défaut 'trace.log' si non défini)
PIN_LOG = data/log/trace.log

# Chemin vers le fichier contenant le secret
KEY_FILE = key.log

[OUTPUT FILES]
# Chemin
RESULT_LOG = data/log/analyse.log
